<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {   $values=[
        ['Áo dài Ái Minh', 7, 1, 10, '2023-12-03', '\r\nÁo dài Ái Minh, một biểu tượng trang phục truyền thống của người Việt, nổi bật với vẻ đẹp thanh lịch và sự tinh tế trong từng đường may. Chiếc áo dài này thường có thiết kế ôm sát vóc dáng, tạo nên sự gọn gàng và quý phái. Được làm từ những chất liệu như lụa, gấm, hoặc voan, áo dài Ái Minh mang lại cảm giác mềm mại, thoải mái cho người mặc.', 'Mặt trước của áo dài thường được trang trí với những đường thêu hoa văn tinh xảo, tạo nên điểm nhấn nghệ thuật độc đáo. Những họa tiết truyền thống như hoa sen, đào, hay những chi tiết nhỏ như lưới ren cũng thường xuất hiện trên bề mặt áo, thể hiện sự kỹ thuật cao trong quá trình sản xuất.'],
        ['Áo dài Viên Minh', 7, 0, 5, '2023-12-02', 'Áo dài Viên Minh, với tên gọi ấn tượng, không chỉ là một trang phục truyền thống mà còn là biểu tượng của sự thanh lịch và sang trọng trong trang phục Việt Nam. Chiếc áo dài này thường được thiết kế với những đường cắt tinh tế, tôn lên vẻ đẹp tự nhiên của người mặc.', 'Áo dài Viên Minh thường có kiểu cổ cao và tay dài, tạo nên sự đằm thắm và trang trí. Chất liệu vải thường là những loại cao cấp như lụa, satin, hoặc nhung, mang lại cảm giác mềm mại và sang trọng. Áo dài được may kỹ lưỡng, với những đường may chắc chắn và tinh tế, tạo nên sự hoàn hảo trong từng chi tiết.'],
        ['Áo Thun Mula ', 1, 1, 3, '2023-12-06', 'Áo thun Mula không chỉ là một sản phẩm thời trang mà còn là biểu tượng của sự thoải mái và phong cách hiện đại. Với chất liệu vải cao cấp và kiểu dáng linh hoạt, áo thun Mula đã chinh phục người mặc bằng sự đơn giản và tinh tế.', 'Chất liệu vải thường là cotton, giúp áo thun Mula thoáng khí và thoải mái. Thiết kế áo thường rất đa dạng, từ áo cổ tròn cơ bản đến áo cổ polo hoặc áo có hình in và thông điệp thú vị. Mọi chi tiết đều được chú trọng để tạo nên một sản phẩm thời trang đẳng cấp và phản ánh cái nhìn đương đại về phong cách.'],
        ['Áo Sơ Mi Yeolan', 2, 1, 2, '2023-12-04', 'Áo sơ mi Yeolan ngắn là một item thời trang đang rất được ưa chuộng trong thời gian gần đây. Với thiết kế đơn giản nhưng không kém phần tinh tế, áo sơ mi Yeolan ngắn mang đến vẻ ngoài trẻ trung, năng động cho người mặc.', 'Áo sơ mi Yeolan ngắn được may từ chất liệu cotton thoáng mát, thấm hút mồ hôi tốt, mang lại cảm giác thoải mái khi mặc. Áo có form dáng rộng rãi, thoải mái, không ôm sát cơ thể, phù hợp với nhiều dáng người khác nhau. Cổ áo sơ mi Yeolan ngắn là cổ bẻ truyền thống, được may tỉ mỉ, chắc chắn. Cúc áo sơ mi được làm từ chất liệu nhựa cao cấp, có độ bền cao.'],
        ['Áo Kiểu Jae', 3, 1, 5, '2023-12-06', 'Áo kiểu Jae là một loại áo sơ mi có thiết kế đơn giản, thanh lịch, phù hợp với cả nam và nữ. Áo có phần cổ bẻ, tay dài, thường được may từ chất liệu cotton hoặc linen.\r\n\r\nÁo kiểu Jae có thiết kế đơn giản, không cầu kỳ, nhưng vẫn toát lên vẻ thanh lịch, tinh tế. Áo có phần cổ bẻ truyền thống, được may tỉ mỉ, chắc chắn. Tay áo dài, có thể xắn lên hoặc buông xuống tùy theo sở thích.', 'Chất liệu: Áo kiểu Jae thường được may từ chất liệu cotton hoặc linen.\r\nForm dáng: Áo có form dáng vừa vặn, không ôm sát cơ thể, phù hợp với nhiều dáng người khác nhau.\r\nCổ áo: Cổ áo sơ mi Jae là cổ bẻ truyền thống, được may tỉ mỉ, chắc chắn.\r\nTay áo: Tay áo dài, có thể xắn lên hoặc buông xuống tùy theo sở thích.\r\nMàu sắc: Áo kiểu Jae có nhiều màu sắc đa dạng để bạn lựa chọn, phù hợp với nhiều phong cách khác nhau.'],
        ['Quần Short Arian', 4, 0, 1, '2023-12-04', 'Quần short Arian là một loại quần short được thiết kế đơn giản, năng động, phù hợp với cả nam và nữ. Quần có phần cạp cao, ống rộng, thường được may từ chất liệu cotton hoặc denim.\r\n\r\n', 'Chất liệu: Quần short Arian thường được may từ chất liệu cotton hoặc denim.\r\nForm dáng: Quần có form dáng rộng rãi, thoải mái, không ôm sát cơ thể, phù hợp với nhiều dáng người khác nhau.\r\nCạp quần: Cạp quần Arian là cạp cao, được may tỉ mỉ, chắc chắn.'],
        ['Chân Váy Camela', 5, 0, 2, '2023-12-03', 'Chân váy Camela là một loại chân váy được thiết kế đơn giản, thanh lịch, phù hợp với mọi dáng người. Chân váy có phần cạp cao, xòe rộng, thường được may từ chất liệu cotton hoặc linen.\r\nChân váy Camela có thiết kế đơn giản, không cầu kỳ, nhưng vẫn toát lên vẻ thanh lịch, tinh tế. Chân váy có phần cạp cao, giúp tôn lên vòng eo thon gọn. Phần chân váy xòe rộng, mang đến vẻ ngoài nữ tính, dịu dàng.', 'Chất liệu: Chân váy Camela thường được may từ chất liệu cotton hoặc linen.\r\nForm dáng: Chân váy có form dáng xòe rộng, thoải mái, không ôm sát cơ thể, phù hợp với nhiều dáng người khác nhau.\r\nCạp váy: Cạp váy Camela là cạp cao, được may tỉ mỉ, chắc chắn.'],
        ['Váy Kera', 6, 1, 1, '2023-12-04', 'Váy Kera là một loại váy được thiết kế đơn giản, thanh lịch, phù hợp với mọi dáng người. Váy có phần cổ chữ V, tay dài, thường được may từ chất liệu cotton hoặc linen.', 'Chất liệu: Váy Kera thường được may từ chất liệu cotton hoặc linen.\r\nForm dáng: Váy có form dáng suông rộng, thoải mái, không ôm sát cơ thể, phù hợp với nhiều dáng người khác nhau.\r\nCổ váy: Cổ váy Kera là cổ chữ V, được may tỉ mỉ, chắc chắn.'],
        ['Áo dài Kim Minh', 7, 1, 110, '2023-12-01', 'Áo dài Kim Minh là thương hiệu áo dài nổi tiếng tại Việt Nam, được thành lập từ năm 2005. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng đa dạng.', 'Áo dài truyền thống của Kim Minh được thiết kế theo form dáng chuẩn mực, với phần thân trước và thân sau dài bằng nhau, phần tay dài có thể là tay lỡ hoặc tay dài. Cổ áo có thể là cổ thuyền, cổ tròn hoặc cổ cao, phù hợp với mọi vóc dáng.'],
        [ 'Áo dài Uyển Minh', 7, 1, 15, '2023-12-02', 'Áo dài Uyển Minh là thương hiệu áo dài được thành lập từ năm 2019 bởi nhà thiết kế trẻ Lê Thị Uyển Minh. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng trẻ trung, thanh lịch.', 'Áo dài truyền thống của Uyển Minh được thiết kế theo form dáng chuẩn mực, với phần thân trước và thân sau dài bằng nhau, phần tay dài có thể là tay lỡ hoặc tay dài. Cổ áo có thể là cổ thuyền, cổ tròn hoặc cổ cao, phù hợp với mọi vóc dáng.'],
        ['Áo dài Tuệ Minh', 7, 1, 0, '2023-12-03', 'Áo dài Tuệ Minh là thương hiệu áo dài được thành lập từ năm 2020 bởi nhà thiết kế trẻ Nguyễn Thị Tuệ Minh. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng đơn giản, thanh lịch.', 'Áo dài truyền thống của Tuệ Minh được thiết kế theo form dáng chuẩn mực, với phần thân trước và thân sau dài bằng nhau, phần tay dài có thể là tay lỡ hoặc tay dài. Cổ áo có thể là cổ thuyền, cổ tròn hoặc cổ cao, phù hợp với mọi vóc dáng.'],
        ['Áo dài Ngư Minh', 7, 1, 0, '2023-12-06', 'Áo dài Ngư Minh là thương hiệu áo dài mới nổi, được thành lập từ năm 2023. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng độc đáo, mới lạ.', 'Áo dài truyền thống của Ngư Minh được thiết kế theo form dáng chuẩn mực, với phần thân trước và thân sau dài bằng nhau, phần tay dài có thể là tay lỡ hoặc tay dài. Cổ áo có thể là cổ thuyền, cổ tròn hoặc cổ cao, phù hợp với mọi vóc dáng.'],
        ['Áo dài Nhã Minh', 7, 1, 15, '2023-12-04', 'Áo dài Nhã Minh là thương hiệu áo dài được thành lập từ năm 2022. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng trẻ trung, năng động.', 'Áo dài truyền thống của Nhã Minh được thiết kế theo form dáng chuẩn mực, với phần thân trước và thân sau dài bằng nhau, phần tay dài có thể là tay lỡ hoặc tay dài. Cổ áo có thể là cổ thuyền, cổ tròn hoặc cổ cao, phù hợp với mọi vóc dáng.'],
        ['Áo Dài Ý Minh', 7, 1, 22, '2023-12-02', 'Áo Dài Ý Minh là thương hiệu áo dài được thành lập từ năm 2022. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng đơn giản, thanh lịch.', 'Với chất lượng vượt trội và kiểu dáng đơn giản, thanh lịch, áo dài Ý Minh là lựa chọn lý tưởng cho những cô nàng yêu thích áo dài truyền thống và cách tân, nhưng muốn thể hiện phong cách thanh lịch, trang nhã của mình.'],
        ['Áo dài Diệp Minh', 7, 1, 11, '2023-12-02', 'Áo dài Diệp Minh là thương hiệu áo dài được thành lập từ năm 2023. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng trẻ trung, thanh lịch.', 'Áo dài Diệp Minh là thương hiệu áo dài được thành lập từ năm 2023. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng trẻ trung, thanh lịch.'],
        ['Áo Dài Khánh Mỹ', 7, 1, 11, '2023-12-06', 'Áo Dài Khánh Mỹ là thương hiệu áo dài được thành lập từ năm 2022. Thương hiệu này chuyên thiết kế và sản xuất các mẫu áo dài truyền thống và cách tân, với chất liệu cao cấp và kiểu dáng đơn giản, thanh lịch.', 'Áo dài truyền thống của Khánh Mỹ được thiết kế theo form dáng chuẩn mực, với phần thân trước và thân sau dài bằng nhau, phần tay dài có thể là tay lỡ hoặc tay dài. Cổ áo có thể là cổ thuyền, cổ tròn hoặc cổ cao, phù hợp với mọi vóc dáng.'],
        ['Áo Thun Redvelvet', 1, 1, 11, '2023-12-03', 'Áo thun Red Velvet là một trong những mẫu áo thun được yêu thích nhất hiện nay, đặc biệt là đối với những fan hâm mộ của nhóm nhạc nữ Kpop Red Velvet. Áo thun Red Velvet có nhiều mẫu mã đa dạng, với thiết kế đơn giản, trẻ trung, năng động, phù hợp với mọi lứa tuổi.', 'Chất liệu vải: Áo thun Red Velvet được làm từ chất liệu cotton 100%, mềm mại, thấm hút mồ hôi tốt, mang đến cảm giác thoải mái cho người mặc.\r\nGiá thành: Áo thun Red Velvet có giá thành dao động từ 150.000 đến 300.000 đồng, tùy thuộc vào chất liệu vải, mẫu mã và kích thước áo.'],
        ['Áo Thun Chic', 1, 1, 6, '2023-12-06', 'Áo thun Red Velvet là một trong những mẫu áo thun được yêu thích nhất hiện nay, đặc biệt là đối với những fan hâm mộ của nhóm nhạc nữ Kpop Red Velvet. Áo thun Red Velvet có nhiều mẫu mã đa dạng, với thiết kế đơn giản, trẻ trung, năng động, phù hợp với mọi lứa tuổi.', 'Áo thun Red Velvet logo: Đây là mẫu áo thun đơn giản, với thiết kế logo của nhóm nhạc Red Velvet ở mặt trước áo. Áo thun Red Velvet logo mang đến vẻ đẹp trẻ trung, năng động cho người mặc.\r\nÁo thun Red Velvet hình ảnh: Đây là mẫu áo thun với thiết kế hình ảnh của các thành viên nhóm nhạc Red Velvet ở mặt trước áo. Áo thun Red Velvet hình ảnh mang đến vẻ đẹp đáng yêu, cá tính cho người mặc.'],
        ['Sơ Mi Tarik', 2, 1, 4, '2023-12-01', 'Sơ Mi Tarik được đánh giá cao bởi chất lượng vượt trội, từ chất liệu vải đến kỹ thuật may đo. Vải sơ mi Tarik được nhập khẩu từ các thương hiệu nổi tiếng như Thái Tuấn, Bảo Lộc,... với độ bền cao, mềm mại và thấm hút mồ hôi tốt. Kỹ thuật may đo của sơ mi Tarik được thực hiện bởi những thợ may lành nghề, tỉ mỉ đến từng đường kim mũi chỉ.', 'Sơ mi trơn màu sắc đơn giản: Đây là mẫu sơ mi đơn giản, với thiết kế trơn màu sắc đơn giản. Sơ mi trơn màu sắc đơn giản mang đến vẻ đẹp trẻ trung, năng động cho người mặc.\r\nSơ mi họa tiết nổi bật: Đây là mẫu sơ mi với thiết kế họa tiết nổi bật, bắt mắt. Sơ mi họa tiết nổi bật mang đến vẻ đẹp cá tính, mạnh mẽ cho người mặc.'],
        ['Áo Sơ Mi Cici', 2, 1, 4, '2023-12-04', 'Áo Sơ Mi Cici được đánh giá cao bởi chất lượng vượt trội, từ chất liệu vải đến kỹ thuật may đo. Vải sơ mi Cici được nhập khẩu từ các thương hiệu nổi tiếng như Thái Tuấn, Bảo Lộc,... với độ bền cao, mềm mại và thấm hút mồ hôi tốt. Kỹ thuật may đo của sơ mi Cici được thực hiện bởi những thợ may lành nghề, tỉ mỉ đến từng đường kim mũi chỉ.', 'Sơ mi trơn màu sắc đơn giản: Đây là mẫu sơ mi đơn giản, với thiết kế trơn màu sắc đơn giản. Sơ mi trơn màu sắc đơn giản mang đến vẻ đẹp thanh lịch, trang nhã cho người mặc.\r\nSơ mi họa tiết nhẹ nhàng: Đây là mẫu sơ mi với thiết kế họa tiết nhẹ nhàng, tinh tế. Sơ mi họa tiết nhẹ nhàng mang đến vẻ đẹp thanh lịch, trẻ trung cho người mặc.']
        ];
        $dataToInsert = array_map(function ($item) {
            return [
                'name' => $item[0],
                'id_category' => $item[1],
                'dacbiet' => $item[2],
                'luotxem'=>$item[3],
                'ngaylap'=>$item[4],
                'mota'=>$item[5],
                'chitiet'=>$item[6],
            ];
        }, $values);
        DB::table('products')->insert($dataToInsert);
        
    }
}
